### ISSUE TITLE
Use Php-client with queue? 

### ISSUE THREAD

**Issue by zilveer** [tarantool-php/client#52] opened 2019-07-24 17:56 UTC
Hi,
I wonder if it is possible to use the Tarantool php-client with the queue system and if so can you please provide an example ?

Regards

**Comment by rybakit** [comment] 2019-07-25 23:02
You can find the example in the queue's [README](https://github.com/tarantool-php/queue#working-with-queue).
tl;dr:

```
use Tarantool\Queue\Queue;
use Tarantool\Client\Client;

$client = Client::fromDefaults();
$queue = new Queue($client, 'my-queue-name');
```

**Comment by zilveer** [comment] 2019-07-26 02:42
@rybakit

Thank you for the response.
Do you mean like this?

```
use Tarantool\Queue\Queue;
use Tarantool\Client\Client;

$client = Client::fromDefaults();
$queue = new Queue($client->executeUpdate('
    CREATE TABLE users ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "email" VARCHAR(255))
'), 'my-queue-name');
```
Regards

**Comment by rybakit** [comment] 2019-07-27 07:44
Closed as duplicate of https://github.com/tarantool-php/queue/issues/16.

**Closed as completed by rybakit** 2019-07-27 07:44 UTC
