### ISSUE TITLE
memory leaks with SQL - prepared statements

### ISSUE THREAD

**Issue by IVDeg** [tarantool-php/client#83] opened 2023-05-12 05:09 UTC
In our project, we encountered memory leaks when using SQL-prepared statements. It was noticed that if we don't call PreparedStatement::close(), the leaks stop.

**Comment by mhthnz** [comment] 2023-05-13 07:44
It would be useful to have some reproducible examples of memory leak

**Comment by rybakit** [comment] 2023-06-29 20:29
Closing due to lack of details confirming that the problem is in the library.

**Closed as completed by rybakit** 2023-06-29 20:29 UTC
